baseURL = 'https://max011027.github.io/newsite/'
languageCode = 'en-us'
canonifyurls = true
title = '兰州夜市'
theme = 'ananke'
publishDir = "docs"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

